### ISSUE TITLE
Maven cannot resolve dependencies

### ISSUE THREAD

**Issue by ghobona** [adminfaces/admin-showcase-tomcat#2]
Failed to execute goal on project admin-showcase-tomcat: Could not resolve dependencies for project com.github.adminfaces:admin-showcase-tomcat:war:0.0.1-SNAPSHOT: The following artifacts could not be resolved: com.github.adminfaces:admin-template:jar:1.0.0-20170409.194239-17, com.github.adminfaces:admin-theme:jar:1.0.0-20170415.172255-35: Could not find artifact com.github.adminfaces:admin-template:jar:1.0.0-20170409.194239-17 in snapshots (https://oss.sonatype.org/content/repositories/snapshots)

**Comment by rmpestano** [comment]
Hi @ghobona,

can you try it now?

thanks for reporting.

**Comment by njuandedioso** [comment]
thanks you are the best! (Y)
