### ISSUE TITLE
<p:messages> not working

### ISSUE THREAD

**Issue by encinase** [adminfaces/admin-showcase-tomcat#3]
Hi, i have developed a web application using adminFaces and admin-showcase as example.
I guess the template itself has a p:growl somewhere because i never added and still shows my messages from beans.
Now i am trying to use p:messages because i dont want the message to disappeared after some seconds, and i cant make it work, it sill shows the message in a p:growl that i dont know where it is.

`<h:form id="salida">
			<p:outputPanel id="container">
				<p:messages id="mensajesId" showDetail="true" closable="true" for="mensajes" autoUpdate="true" />
				<h:panelGroup layout="block" rendered="#{params.render == true}" style="float:left;overflow-y: auto;height: auto;">
					<p:remoteCommand name="onCellEdit" action="#{params.obtenerParametros}" update="container" />
	 				<p:dataTable id="tablaParams" var="parametro" value="#{params.xmlParams}" editable="true" stickyHeader="true" emptyMessage="No se encontraron datos">
						<p:ajax event="rowEdit" listener="#{params.setNewParamsValue}" oncomplete="onCellEdit()"/>
		       			<p:ajax event="rowEditCancel"/>
						<p:column headerText="XML"  width="100%">
					    	<p:cellEditor>
					    		<f:facet name="output"><h:outputText value="#{parametro.valor}" /></f:facet>
	               				<f:facet name="input"><p:inputText value="#{parametro.valor}" style="width:96%" label="Nuevo valor" /></f:facet>
					        </p:cellEditor>
					    </p:column>
					    <p:column style="width:45px">
				        	<p:rowEditor />
				       	</p:column>
					</p:dataTable>					
				</h:panelGroup>
			</p:outputPanel>
		</h:form>`

Bean:
`public void setNewParamsValue(){
FacesContext.getCurrentInstance().addMessage("mensajes", new FacesMessage("Info: ", "Modified OK!!"));
}`

the bean is called after i edit the column of the table, thats working fine, it executes the setNewParamsValue function, but never shows the messages.

**Comment by rmpestano** [comment]
Hi, take a look at configuration section here: https://adminfaces.github.io/site/docs/latest/#configuration

You can remove the auto-hide feature with `admin.autoHideMessages=false` or remove[ buildin messages](https://github.com/adminfaces/admin-template/blob/fc7ed46993f0605ef468e9ea2a8804746b9e3fb9/src/main/resources/META-INF/resources/admin.xhtml#L137) on template with `admin.renderMessages=false`.

About the growl I need to take a loook at the code because the template doesn't have a growl.

**Comment by encinase** [comment]
Ok, thanks, by setting the renderMessages=true is showing the message twice, one in my p:message and also the template growl (I think).
If i set it to false, only shows on my p:message as i wanted, unfortuntly i only wanted to disabled this for one page and not for the whole project, but never mind with this information i can find a better solution.
Thanks!

**Comment by rmpestano** [comment]
So this issue is about disabling template messages on specific pages?

If yes we can add that easily.

**Comment by encinase** [comment]
Yes, exactly, that is what i want so i can show the messages in an specific
part of the page

**Comment by rmpestano** [comment]
I've created issue adminfaces/admin-template#133 which already got fixed. 

You can try that with admin-template `1.0.0-RC19-SNAPSHOT`. You'll need to enable snapshots repository on your pom.xml:

```
<repositories>
        <repository>
            <snapshots/>
            <id>snapshots</id>
            <name>libs-snapshot</name>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
        </repository>
    </repositories>
```

**Comment by rmpestano** [comment]
Now both `autoHideMessages` and `renderMessages` can be disabled on a specific page via `ui:param`.
